### ISSUE TITLE
Unable to get Gender 

### ISSUE THREAD

**Issue by DharmeshR7** [hansemannn/titanium-google-signin#11]

**Comment by hansemannn** [comment]
Please provide a sample code to reproduce the issue. This won't go anywhere else, thx!

**Comment by DharmeshR7** [comment]
Hi,
@hansemannn thanks for looking into this issue. My code is same as written in example, I've got following response after log in with latest IOS module (1.1.5)

{"user":
{
"authentication":{"idTokenExpirationDate","clientID","accessToken","refreshToken","accessTokenExpirationDate"},

"id",
"scopes":["https://www.googleapis.com/auth/userinfo.profile"],
"profile":{"name","givenName","hasImage":true,"familyName","email"},
"serverAuthCode":null,
"hostedDomain":null
},"bubbles":true,"type":"login","source":{},"cancelBubble":false}

**Comment by hansemannn** [comment]
I looked it up and cannot see any reference to a gender property, either in the native SDK nor in the Titanium implementation. Please leave some links if you think the native one has the property, or file a feature-request at Google to expose it.
