### ISSUE TITLE
Missing support for URL schemes error

### ISSUE THREAD

**Issue by and90** [hansemannn/titanium-google-signin#12]
Hi. I'm experiencing problems with this module. The error is the following:

> Your app is missing support for the following URL schemes: com.googleusercontent.apps..***************-xxxxxxxx

...but I added the scheme correctly in tiapp.xml:
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>CFBundleURLName</key>
      <string>google</string>
      <key>CFBundleURLSchemes</key>
      <array>
	  <string>com.googleusercontent.apps.***************-xxxxxxxx</string>
      </array>
  </dict>
</array>
```
I also added it in LSApplicationQueriesSchemes (https://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme).

Could you help me to find the source of the problem? Any help will be appreciated, Thanks in advance!

Best regards

**Comment by hansemannn** [comment]
Please follow the Google developer guide for integrating the module. Since other devs are using the module in production already, it has to be an issue on your side. Thanks!
