### ISSUE TITLE
Google sign out

### ISSUE THREAD

**Issue by ryancschulz** [hansemannn/titanium-google-signin#14]
Hans-

Thanks for this great module.  How would I go about keeping a user signed-out?  What I'm wanting is to force the user to sign-in and enter their password again after calling the disconnect() method?  Currently, they can re-authenticate without entering their password if you call disconnect() and then signIn().

Any input would be appreciated.

**Comment by hansemannn** [comment]
Hey there, did you try `signOut()` ?

**Comment by ryancschulz** [comment]
Yes - I have called signOut() and nothing seems to happen there.....I don't
see anything in console output like I see when I call disconnect().

**Comment by ryancschulz** [comment]
Hans-

Hate to bother you - any way I could get you to look at this?  Several of
my apps are dependent on this module.....I’m certainly willing to pay you
for your time.

Thanks.

**Comment by hansemannn** [comment]
I've just updated the library to the latest version. If `signOut` does not work and `loggedIn` still returns `true` (this property is new), then it's likely a Google issue. The module only wraps the native functionality.

**Comment by ryancschulz** [comment]
OK - I'm getting some build errors.  Looks like maybe the
GoogleAppUtilities and GoogleSymbolUtilities were not included in the
"platform" directory?

**Comment by hansemannn** [comment]
https://github.com/hansemannn/titanium-google-signin/releases/tag/v1.2.1
