### ISSUE TITLE
How to call Google Calendar api after login could you please share code 

### ISSUE THREAD

**Issue by ravindrababuvidya** [hansemannn/titanium-google-signin#16]
I am using you build ti.googlesignin module. Successfully working in my workspace but how to call after getting response google calendar api could you please provide some code

**Comment by hansemannn** [comment]
Sorry, but this is not scope of this project. You should use Hyperloop and the `GoogleAPIClientForREST/Calendar` pod by following the [Calendar API guide](https://developers.google.com/google-apps/calendar/quickstart/ios).
