### ISSUE TITLE
Unable to get the Google Authentication Access Token?

### ISSUE THREAD

**Issue by ChanakyaSrinivas** [hansemannn/titanium-google-signin#17]
Hi All,

How to get Google Authentication Access Token for titanium mobile apps (ios and android) ?

**Comment by hansemannn** [comment]
Please see the answer on Slack, this is only the iOS module and works for others. You should look out for Android help on Slack or the [Android version](https://github.com/AppWerft/Ti.GoogleSignIn) of this module.
