### ISSUE TITLE
Your app is missing support

### ISSUE THREAD

**Issue by AhmedMSayed** [hansemannn/titanium-google-signin#18]
Hey Hans, please help me with this issue.

`Your app is missing support for the following URL schemes: com.googleusercontent.apps.127078586633-vfcjhebv09887vbm4651l983aqffu2hq`

I got CLIENT_ID and REVERSED_CLIENT_ID from GoogleService-Info file

CLIENT_ID : 
127078586633-vfcjhebv09887vbm4651l983aqffu2hq.apps.googleusercontent.com
REVERSED_CLIENT_ID :
com.googleusercontent.apps.127078586633-vfcjhebv09887vbm4651l983aqffu2hq

and added the CLIENT_ID in google.initialize and REVERSED_CLIENT_ID in CFBundleURLSchemes.

**Comment by hansemannn** [comment]
This is not a module issue but a misconfigured project. You have to add the url-scheme as described in the log. Add to the tiapp.xml plist section:
```xml
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLName</key>
		<string>google</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>com.googleusercontent.apps.127078586633-vfcjhebv09887vbm4651l983aqffu2hq</string>
		</array>
	</dict>
</array>
```

**Comment by AhmedMSayed** [comment]
Yes i copy it from readme and added it in plist section with REVERSED_CLIENT_ID.
and try your code now but still have the issue.

<plist>
			<key>CFBundleURLTypes</key>
			<array>
				<dict>
					<key>CFBundleTypeRole</key>
					<string>Editor</string>
					<key>CFBundleURLName</key>
					<string>google</string>
					<key>CFBundleURLSchemes</key>
					<array>
						<string>com.googleusercontent.apps.127078586633-vfcjhebv09887vbm4651l983aqffu2hq</string>
					</array>
				</dict>
			</array>
			<dict>
				<key>UISupportedInterfaceOrientations~iphone</key>
				<array>
					<string>UIInterfaceOrientationPortrait</string>
				</array>
				<key>UISupportedInterfaceOrientations~ipad</key>
				<array>
					<string>UIInterfaceOrientationPortrait</string>
					<string>UIInterfaceOrientationPortraitUpsideDown</string>
					<string>UIInterfaceOrientationLandscapeLeft</string>
					<string>UIInterfaceOrientationLandscapeRight</string>
				</array>
				<key>UIRequiresPersistentWiFi</key>
				<false/>
				<key>UIPrerenderedIcon</key>
				<false/>
				<key>UIStatusBarHidden</key>
				<false/>
				<key>UIStatusBarStyle</key>
				<string>UIStatusBarStyleDefault</string>
			</dict>
		</plist>

**Comment by AhmedMSayed** [comment]
I added your code in dict section not in plist section and it's worked now.

Thanks Hans
