### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-google-signin#19]
![simulator screen shot - iphone 5s - 2018-02-13 at 14 45 35](https://user-images.githubusercontent.com/10107024/36162002-642afde8-10cc-11e8-8094-66c7be9485ab.png)

```js
const Google = require('ti.googlesignin');

  Google.initialize({
    clientID: Alloy.CFG.Google.SignIn // -> 789544906850-xxxxxxx.apps.googleusercontent.com

    // Optional properties:
    , scopes: ['https://www.googleapis.com/auth/plus.login'] // See https://developers.google.com/identity/protocols/googlescopes for more
    , language: 'pt-BR' // Or 'de-DE', 'en-US', etc.
    , loginHint: 'Titanium rocks!'
  });
```

I'm using `Web Client ID` as `clientID` as mentioned on Android's module version

**Comment by hansemannn** [comment]
You need native client ID's for iOS, please read the docs carefully.
