### ISSUE TITLE
Architectures not found. arm67

### ISSUE THREAD

**Issue by sagarsneo** [hansemannn/titanium-google-signin#20]
Downloaded the stable version of the module on iphoneX ios 11

[INFO] :   Ti.Platform.name : iPhone OS
[ERROR] :  Script Error Couldn't find module: ti.googlesignin for architecture: arm64

**Comment by hansemannn** [comment]
Which SDK are you running on? Please ensure you have copied the module to your project or installed it to your global module directory and check if you use at least 5.5.1 or later. As other developers use this in production already, it has to be something on your end. P.S.: It's arm64, not arm67.

**Comment by sagarsneo** [comment]
Yea. arm67 :)

The appc sdk I am using is 7.0.2.GA


got confused with this on simulator. 
![image](https://user-images.githubusercontent.com/20925212/36251927-f272f1c6-1268-11e8-8c42-1018456388dd.png)

On iphone
![img_dba6e515071c-1](https://user-images.githubusercontent.com/20925212/36252084-7ef24e44-1269-11e8-80f6-48e774b6d1aa.jpeg)



Still will cross check with points you mentioned.
