### ISSUE TITLE
400 invalid_request

### ISSUE THREAD

**Issue by anurag12345** [hansemannn/titanium-google-signin#22]
Getting Error 400.
Error : invalid_request
Custom scheme URIs are not allowed for "Web" client type.

My entry in tiapp.xml

```
**<key>CFBundleTypeRole</key>
<string>Editor</string>
<key>CFBundleURLName</key>
<string>google</string>
<key>CFBundleURLSchemes</key>
<array>
		<string>com.googleusercontent.apps.*******************</string>
</array>**
```

![simulator screen shot - iphone 7 - 2018-05-12 at 23 41 38](https://user-images.githubusercontent.com/7657256/39960319-64d1710c-563e-11e8-9f5b-bb73531f6032.png)

**Comment by hansemannn** [comment]
your token has to be generated for the native client type
