### ISSUE TITLE
Change language after module initialization

### ISSUE THREAD

**Issue by mawenlihk** [hansemannn/titanium-google-signin#26]
First thanks for providing such a wonderful module for Titanium community 👍👍
I've noticed that we can specify a desired language when invoking `initialize` method. But would it be possible to add a separate method to enable changing the language again _afterwards_? This can be helpful for apps supporting multiple languages~

**Comment by hansemannn** [comment]
Sounds like a good idea! Here you go: https://github.com/hansemannn/titanium-google-signin/releases/tag/v1.4.0

**Comment by mawenlihk** [comment]
Thank you very much @hansemannn !
