### ISSUE TITLE
Failed to build project with this module

### ISSUE THREAD

**Issue by qalbit** [hansemannn/titanium-google-signin#30]
When trying to load sample project received following error:

`[TRACE] :  Undefined symbols for architecture x86_64:`
`[TRACE] :    "_OBJC_CLASS_$_LAContext", referenced from:`
`[TRACE] :        objc-class-ref in GoogleSignIn(MDMPasscodeCache_42de90102bb6814d03833694aafcc99d.o)`
`[TRACE] :  ld: symbol(s) not found for architecture x86_64`
`[TRACE] :  clang`
`[TRACE] :  : error: linker command failed with exit code 1 (use -v to see invocation)`
`[ERROR] :  ** BUILD FAILED **`
`[ERROR] :  The following build commands failed:`
`[ERROR] :  	Ld /Users/qalbit/Documents/axway_ws/FatShares-App/build/iphone/build/Products/Debug-iphonesimulator/FatShares.app/FatShares normal x86_64
[ERROR] :  (1 failure)`

**Comment by hansemannn** [comment]
add `-framework LocalAuthentication` to the titanium.xcconfig.

**Comment by qalbit** [comment]
Thanks for your quick reply @hansemannn 

But after adding LocalAuthentication Framework I am facing another issues exactly as [this.](https://github.com/hansemannn/titanium-firebase-core/issues/21)
