### ISSUE TITLE
Cannot get iOS app to build with googlelSignin module

### ISSUE THREAD

**Issue by raybelisle** [hansemannn/titanium-google-signin#36]
I am currently using Ti SDK 9.3.2 and xCode 12.4 and Firebase Core 6.1.1 module installed for my project. I have downloaded ti.googlesignin for iOS version 4.1.0 and 4.2.0. Whenever I try to compile the app with the module reference in the tiapp.xml file, the compile fails with the following error when setting log-level to trace. If I remove the module reference, the app compiles properly.

`[TRACE] ld: warning: directory not found for option '-L/Users/user/Documents/myapp/build/iphone/lib'
[TRACE] ld: warning: ignoring file /Users/user/Documents/myapp/build/iphone/build/Products/Debug-iphonesimulator/libti.googlesignin.a, building for iOS Simulator-i386 but attempting to link with file built for iOS Simulator-x86_64
[TRACE] ld: warning: ignoring file /Users/user/Documents/myapp/build/iphone/build/Products/Debug-iphonesimulator/libfirebase.core.a, missing required architecture i386 in file /Users/user/Documents/myapp/build/iphone/build/Products/Debug-iphonesimulator/libfirebase.core.a (2 slices)
[TRACE] ld: warning: Could not find or use auto-linked framework 'FBLPromises'
[TRACE] Undefined symbols for architecture i386:
[TRACE]   "_OBJC_CLASS_$_LAContext", referenced from:
[TRACE]       objc-class-ref in GoogleSignIn(MDMPasscodeCache_9db9a55228f5f3452187a7c521fe0062.o)
[TRACE] ld: symbol(s) not found for architecture i386
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] ** BUILD FAILED **`

Any idea what might be going on?

**Comment by hansemannn** [comment]
It seems like the `-framework LocalAuthentication` line is missing in the module.xcconfig. As a workaround, include ti.identify, which links to it as well. Feel free to submit a PR with the change.

**Comment by raybelisle** [comment]
I'll take a look. Thanks!

**Comment by hansemannn** [comment]
Closing for now, especially with the new version!
