### ISSUE TITLE
Scopes and permissions

### ISSUE THREAD

**Issue by qaqee-DK** [hansemannn/titanium-google-signin#40]
It's not clear how to properly use/add scopes after the 5.0.0 breaking change/deprecation. README.md still shows to keep using them as an object on ```GoogleSignIn.initialize```, however, scopes there are flagged as removed and they are not recognized: they don't return as valid granted scopes.

```
GoogleSignIn.initialize({
    clientID: '<client-id>',
    scopes: ['https://www.googleapis.com/auth/drive.file']
});
```

**Comment by hansemannn** [comment]
Merged and [released,](https://github.com/hansemannn/titanium-google-signin/releases/tag/ios-6.0.2) thank you!
