### ISSUE TITLE
Conflict with ti.map 3.1.1

### ISSUE THREAD

**Issue by ryansoy** [hansemannn/titanium-google-signin#7]
After i added then build it error conflict with ti.map.
Please help me. i try find but no solution on it. (SDK 6.0.3)

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/internal/zze;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:334)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:244)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/firebase/FirebaseApiNotAvailableException;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:334)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:244)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  2 errors; aborting

**Comment by hansemannn** [comment]
This error looks Android-related. This repository is the iOS one, please open an issue in https://github.com/appwerft/Ti.GoogleSignIn instead.
