### ISSUE TITLE
Error while sign in

### ISSUE THREAD

**Issue by chhatbargaurang** [hansemannn/titanium-google-signin#8]
Module giving me an error while Google.signIn()

[ERROR] :  Script Error {
[ERROR] :      column = 15;
[ERROR] :      line = 171;
[ERROR] :      message = "Your app is missing support for the following URL schemes: "MY_CLIENT_ID";
[ERROR] :      stack = "[native code]\n";
[ERROR] :  }

is there any solution for this?

**Comment by hansemannn** [comment]
It says what it says: You have to register the URL scheme for your app. Add the scheme in your tiapp:
```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>google</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <!-- Example: com.googleusercontent.apps.123456789-xxxxxxxx -->
            <string>YOUR_REVERSE_CLIENT_ID</string>
        </array>
    </dict>
</array>
```
and link it to the Google SignIn capabilities in your Google API Console.

**Comment by chhatbargaurang** [comment]
Its already included.
<ios>
        <enable-launch-screen-storyboard>true</enable-launch-screen-storyboard>
        <use-app-thinning>true</use-app-thinning>
        <plist>
            <dict>
                <key>UISupportedInterfaceOrientations~iphone</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                </array>
                <key>UISupportedInterfaceOrientations~ipad</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                    <string>UIInterfaceOrientationPortraitUpsideDown</string>
                    <string>UIInterfaceOrientationLandscapeLeft</string>
                    <string>UIInterfaceOrientationLandscapeRight</string>
                </array>
                <key>UIRequiresPersistentWiFi</key>
                <false/>
                <key>UIPrerenderedIcon</key>
                <false/>
                <key>UIStatusBarHidden</key>
                <false/>
                <key>UIStatusBarStyle</key>
                <string>UIStatusBarStyleDefault</string>
                <key>CFBundleURLTypes</key>
                <array>
                    <dict>
                        <key>CFBundleTypeRole</key>
                        <string>Editor</string>
                        <key>CFBundleURLName</key>
                        <string>google</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                                        
                            <string>MY_REVERSE_CLIENT_ID</string>
                        </array>
                    </dict>
                </array>
            </dict>
        </plist>
    </ios>

**Comment by hansemannn** [comment]
It has to be the one that you registered. Sorry, but this is no module issue.

**Comment by chhatbargaurang** [comment]
Can you guide me which Credential I have to use for it? I checked it with iOS and Web Application Both.
