### ISSUE TITLE
Main thread

### ISSUE THREAD

**Issue by qaqeeApps** [hansemannn/titanium-google-signin#9]
I think signIn and signInSilently methods should be called from main thread, to avoid Google Sign-in instance issues (such as after an app restart). I had several problems with that. One is reported here: https://github.com/googlesamples/google-services/issues/108
I'll add a code later.

Daniel

**Comment by hansemannn** [comment]
Fixed in https://github.com/hansemannn/titanium-google-signin/releases/tag/v1.1.4!

**Comment by qaqeeApps** [comment]
Nice! Thanks!
